branch-defaults:
  master:
    environment: Diogenesmorph-env
deploy:
  artifact: Dockerrun.aws.json
environment-defaults:
  Diogenesmorph-env:
    branch: null
    repository: null
global:
  application_name: DiogenesMorph
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Docker running on
    64bit Amazon Linux/2.14.1
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
